#!/bin/sh

set -o errexit
set -o nounset
set -o pipefail
shopt -s nullglob

[ $# -gt 0 ] && while [ "${1:0:2}" == '--' ]; do
  OPTION=${1:2};
  [[ $OPTION =~ = ]] && declare "BOCKER_${OPTION/=*/}=${OPTION/*=/}" || declare "BOCKER_${OPTION}=x"; shift;
done

source src/help.sh

[ "$#" -eq 0 ] && bocker_help && exit 1
case $1 in
  pull) shift && bocker_pull "$@" ;;
  help) shift && bocker_help "$@" ;;
  init) shift && bocker_init "$@" ;;
  rm) shift && bocker_rm "$@" ;;
  image) shift && bocker_image "$@" ;;
  ps) shift && bocker_ps "$@" ;;
  run) shift && bocker_run "$@" ;;
  spawn) shift && bocker_spawn "$@" ;;
  exec) shift && bocker_exec "$@" ;;
  kill) shift && bocker_kill "$@" ;;
  logs) shift && bocker_logs "$@" ;;
  commit) shift && bocker_commit "$@" ;;
  *) bocker_help "$0" ;;
esac
